### ISSUE TITLE
Keylogger

### ISSUE THREAD

**Issue by basharhaar** [Obrelix/Windows-Advanced-Keylogger#1]
i cannot find the decryption file for decrypting the log file

**Comment by Obrelix** [comment]
Hello mate! I developed another project in order to decrypting/encrypting files,
you can find it in this repo [here](https://github.com/Obrelix/Base64-File-Encryption)

**Comment by Obrelix** [comment]
Hello again! in order to sent e-mails from the windows powershell its is needed to activate google less secure apps in your google account. Do you have any other issues with this project?
